<?php

namespace App\Filament\Admin\Resources;

use App\Filament\Resources\PatientResource\Pages;
use App\Filament\Resources\PatientResource\RelationManagers;
use App\Models\Patient;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Infolists\Infolist;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;

class PatientResource extends Resource
{
    protected static ?string $model = Patient::class;

    protected static ?string $pluralModelLabel = '患者';

    protected static ?int $navigationSort = 1;

    protected static ?string $navigationGroup = 'Shop';

    protected static ?string $navigationIcon = 'heroicon-o-rectangle-stack';

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('name')
                    ->required()
                    ->maxLength(255),
                Forms\Components\Select::make('type')
                    ->options([
                        'cat' => 'Cat',
                        'dog' => 'Dog',
                        'rabbit' => 'Rabbit'
                    ])
                    ->required(),
                Forms\Components\DatePicker::make('date_of_birth')
                    ->required()
                    ->maxDate(now()),
                Forms\Components\Select::make('owner_id')
                    ->relationship('owner', 'name')
                    ->searchable()
                    ->preload()
                    ->createOptionForm([
                        Forms\Components\TextInput::make('name')->required()->maxLength(255),
                        Forms\Components\TextInput::make('email')->label('Email Address')->email()->required()->maxLength(255),
                        Forms\Components\TextInput::make('phone')->label('Phone Number')->tel()->required()
                    ])
                    ->required()
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('name')->label('名字')->searchable(),
                Tables\Columns\TextColumn::make('type')->label('品种'),
                Tables\Columns\TextColumn::make('date_of_birth')->label('生日')->sortable(),
                Tables\Columns\TextColumn::make('owner.name')->label('主人')->searchable(),
            ])
            ->filters([
                Tables\Filters\SelectFilter::make('type')->options([
                    'cat' => 'Cat',
                    'dog' => 'Dog',
                    'rabbit' => 'Rabbit'
                ])
            ])
            ->actions([
                Tables\Actions\ViewAction::make(),
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            \App\Filament\Admin\Resources\PatientResource\RelationManagers\TreatmentsRelationManager::class
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => \App\Filament\Admin\Resources\PatientResource\Pages\ListPatients::route('/'),
            'create' => \App\Filament\Admin\Resources\PatientResource\Pages\CreatePatient::route('/create'),
            'edit' => \App\Filament\Admin\Resources\PatientResource\Pages\EditPatient::route('/{record}/edit'),
            'view' => \App\Filament\Admin\Resources\PatientResource\Pages\ViewPatient::route('/{record}'),
        ];
    }

    public static function infolist(Infolist $infolist): Infolist
    {
        return parent::infolist($infolist); // TODO: Change the autogenerated stub
    }
}
